# Generated by Django 4.2.18 on 2025-04-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужское'), ('female', 'Женское')], max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
