# Generated by Django 4.2.18 on 2025-04-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('description', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'вопрос/ответ',
                'verbose_name_plural': 'Вопросы/Ответы',
            },
        ),
    ]
