# Generated by Django 4.2.18 on 2025-04-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, help_text='Например: 20 означает скидку 20%', null=True, verbose_name='Процентная скидка (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Например: -500 означает скидку  500 сомов', max_digits=12, null=True, verbose_name='Фиксированная скидка (в валюте)'),
        ),
    ]
