# Generated by Django 4.2.18 on 2025-04-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discount_percent_product_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название видео(кликбайт)')),
                ('link_video', models.CharField(help_text='вставляйте ссылку на источник. Например из youtube', max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'влог',
                'verbose_name_plural': 'Влог',
            },
        ),
    ]
