# Generated by Django 4.2.18 on 2025-04-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_videoblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoblog',
            name='link_video',
            field=models.TextField(help_text='вставляйте ссылку на источник. Например из youtube', max_length=255, verbose_name='Ссылка'),
        ),
    ]
